sudo: required
services: 
 - docker

 before_install:
  - docker build -t ashleychristensen/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run ashleychristensen/react-test npm test -- --coverage #make sure script exits with 0 or not 

after_success: #prod versions build
  - docker build -t ashleychristensen/multi-client ./client
  - docker build -t ashleychristensen/multi-nginx ./nginx
  - docker build -t ashleychristensen/multi-server ./server
  - docker build -t ashleychristensen/multi-worker ./worker



  #not docker run ... npm test -- -- coverage
  #docker run -e CI=true ashleychristensen/react-test npm test